services:
  backend:
    build:
      context: ./back
    ports:
      - "8004:8004"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./storage/user-files:/app/storage/user-files
    restart: unless-stopped

  frontend:
    build:
      context: ./front
    ports:
      - "3002:3000"
    env_file:
      - path: .env
        required: false
    depends_on:
      - backend
    restart: unless-stopped
